[tool.poetry]
name = "uniswap-python"
version = "0.4.7"
description = "An unofficial Python wrapper for the Uniswap exchange"
repository = "https://github.com/iancmoritz/uniswap-python"
readme = "README.md"
keywords = ["uniswap", "ethereum", "exchange", "trading"]
authors = ["Shane Fontaine <shane6fontaine@gmail.com>", "Erik Bjäreholt <erik@bjareho.lt>", "Ian Moritz <icm35@cornell.edu>"]
license = "MIT"
packages = [
    { include = "uniswap" },
]
include = ["uniswap/assets/*.abi", "uniswap/assets/*/*.abi"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Information Technology",
    "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.scripts]
unipy = "uniswap:main"

[tool.poetry.dependencies]
python = "^3.7"
web3 = "^5.12.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
mypy = "*"
black = "^19.10b0"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
pytest-dotenv = "^0.5.2"
python-dotenv = "^0.14.0"
flake8 = "^3.8.3"
Sphinx = "^3.5.4"
sphinx-book-theme = "^0.1.0"
sphinx-click = "^2.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
